-- PUBLIC.MIGRATION_LOG definition

-- Drop table

-- DROP TABLE PUBLIC.MIGRATION_LOG;

CREATE TABLE PUBLIC.MIGRATION_LOG (
	ID INTEGER NOT NULL IDENTITY,
	DATABASE_VERSION VARCHAR(255),
	DATE_EXECUTION TIMESTAMP,
	EXECUTION_LOG VARCHAR(16777216),
	IS_ERROR BOOLEAN,
	SCRIPT_NAME VARCHAR(255),
	CONSTRAINT SYS_PK_10155 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10155_10156 ON PUBLIC.MIGRATION_LOG (ID);


-- PUBLIC.GLOBAL_CONFIGURATION definition

-- Drop table

-- DROP TABLE PUBLIC.GLOBAL_CONFIGURATION;

CREATE TABLE PUBLIC.GLOBAL_CONFIGURATION (
	ID INTEGER NOT NULL IDENTITY,
	OPEN_LINK_BROWSER_OPTS VARCHAR(255),
	CONSTRAINT SYS_PK_11778 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_11778_15478 ON PUBLIC.GLOBAL_CONFIGURATION (ID);


-- PUBLIC.MODEL definition

-- Drop table

-- DROP TABLE PUBLIC.MODEL;

CREATE TABLE PUBLIC.MODEL (
	ID INTEGER NOT NULL IDENTITY,
	APPLICATION VARCHAR(255),
	CONTACT VARCHAR(255),
	VERSION VARCHAR(255),
	VERSION_ORIGIN VARCHAR(255),
	PCMM_SCHEMA_PATH VARCHAR(255),
	PIRT_SCHEMA_PATH VARCHAR(255),
	COM_REQUIREMENT_SCHEMA_PATH VARCHAR(255),
	COM_UNCERTAINTY_SCHEMA_PATH VARCHAR(255),
	CONSTRAINT SYS_PK_10159 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10159_10160 ON PUBLIC.MODEL (ID);


-- PUBLIC.PCMM_ASSESS_LEVEL definition

-- Drop table

-- DROP TABLE PUBLIC.PCMM_ASSESS_LEVEL;

CREATE TABLE PUBLIC.PCMM_ASSESS_LEVEL (
	ID INTEGER NOT NULL IDENTITY,
	CODE INTEGER,
	FIXED_COLOR VARCHAR(255),
	NAME VARCHAR(255),
	CONSTRAINT SYS_PK_10185 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10185_10186 ON PUBLIC.PCMM_ASSESS_LEVEL (ID);


-- PUBLIC.PCMM_OPTION definition

-- Drop table

-- DROP TABLE PUBLIC.PCMM_OPTION;

CREATE TABLE PUBLIC.PCMM_OPTION (
	ID INTEGER NOT NULL IDENTITY,
	PHASE VARCHAR(255),
	CONSTRAINT SYS_PK_10195 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10195_10196 ON PUBLIC.PCMM_OPTION (ID);


-- PUBLIC.PIRT_ADEQUACY_COLUMN definition

-- Drop table

-- DROP TABLE PUBLIC.PIRT_ADEQUACY_COLUMN;

CREATE TABLE PUBLIC.PIRT_ADEQUACY_COLUMN (
	ID INTEGER NOT NULL IDENTITY,
	ID_LABEL VARCHAR(255),
	NAME VARCHAR(255),
	"TYPE" VARCHAR(255),
	CONSTRAINT SYS_PK_10263 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10263_10264 ON PUBLIC.PIRT_ADEQUACY_COLUMN (ID);


-- PUBLIC.PIRT_ADEQUACY_COLUMN_GUIDELINE definition

-- Drop table

-- DROP TABLE PUBLIC.PIRT_ADEQUACY_COLUMN_GUIDELINE;

CREATE TABLE PUBLIC.PIRT_ADEQUACY_COLUMN_GUIDELINE (
	ID INTEGER NOT NULL IDENTITY,
	DESCRIPTION VARCHAR(16777216),
	NAME VARCHAR(255),
	CONSTRAINT SYS_PK_10267 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10267_10268 ON PUBLIC.PIRT_ADEQUACY_COLUMN_GUIDELINE (ID);


-- PUBLIC.PIRT_DESC_HEADER definition

-- Drop table

-- DROP TABLE PUBLIC.PIRT_DESC_HEADER;

CREATE TABLE PUBLIC.PIRT_DESC_HEADER (
	ID INTEGER NOT NULL IDENTITY,
	ID_LABEL VARCHAR(255),
	NAME VARCHAR(255),
	CONSTRAINT SYS_PK_10277 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10277_10278 ON PUBLIC.PIRT_DESC_HEADER (ID);


-- PUBLIC.PIRT_LEVEL_DIFF_COLOR definition

-- Drop table

-- DROP TABLE PUBLIC.PIRT_LEVEL_DIFF_COLOR;

CREATE TABLE PUBLIC.PIRT_LEVEL_DIFF_COLOR (
	ID INTEGER NOT NULL IDENTITY,
	COLOR VARCHAR(255),
	DESCRIPTION VARCHAR(16777216),
	EXPLANATION VARCHAR(16777216),
	MAX INTEGER,
	MIN INTEGER,
	CONSTRAINT SYS_PK_10281 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10281_10282 ON PUBLIC.PIRT_LEVEL_DIFF_COLOR (ID);


-- PUBLIC.PIRT_LEVEL_IMPORTANCE definition

-- Drop table

-- DROP TABLE PUBLIC.PIRT_LEVEL_IMPORTANCE;

CREATE TABLE PUBLIC.PIRT_LEVEL_IMPORTANCE (
	ID INTEGER NOT NULL IDENTITY,
	FIXEDCOLOR VARCHAR(255),
	FIXEDCOLORDESC VARCHAR(16777216),
	ID_LABEL VARCHAR(255),
	LABEL VARCHAR(255),
	"LEVEL" INTEGER,
	NAME VARCHAR(255),
	CONSTRAINT SYS_PK_10285 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10285_10286 ON PUBLIC.PIRT_LEVEL_IMPORTANCE (ID);


-- PUBLIC."ROLE" definition

-- Drop table

-- DROP TABLE PUBLIC."ROLE";

CREATE TABLE PUBLIC."ROLE" (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(255),
	CONSTRAINT SYS_PK_10301 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10301_10302 ON PUBLIC."ROLE" (ID);


-- PUBLIC.COM_REQUIREMENT_PARAM definition

-- Drop table

-- DROP TABLE PUBLIC.COM_REQUIREMENT_PARAM;

CREATE TABLE PUBLIC.COM_REQUIREMENT_PARAM (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(16777216),
	"TYPE" VARCHAR(255),
	MODEL_ID INTEGER,
	PARENT_ID INTEGER,
	"LEVEL" VARCHAR(16) DEFAULT '*',
	REQUIRED VARCHAR(255),
	DEFAULT_VALUE VARCHAR(255),
	CONSTRAINT SYS_PK_10129 PRIMARY KEY (ID),
	CONSTRAINT FK_COM_REQUIREMENT_PARAM_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES PUBLIC.MODEL(ID)
);
CREATE INDEX SYS_IDX_FK_COM_REQUIREMENT_PARAM_MODEL_ID_10457 ON PUBLIC.COM_REQUIREMENT_PARAM (MODEL_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10129_10130 ON PUBLIC.COM_REQUIREMENT_PARAM (ID);


-- PUBLIC.COM_REQUIREMENT_PARAM_CONSTRAINT definition

-- Drop table

-- DROP TABLE PUBLIC.COM_REQUIREMENT_PARAM_CONSTRAINT;

CREATE TABLE PUBLIC.COM_REQUIREMENT_PARAM_CONSTRAINT (
	ID INTEGER NOT NULL IDENTITY,
	RULE VARCHAR(255),
	"TYPE" VARCHAR(255),
	PARAMETER_ID INTEGER,
	CONSTRAINT SYS_PK_10360 PRIMARY KEY (ID),
	CONSTRAINT FK_COM_REQUIREMENT_PARAM_CONSTRAINT_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.COM_REQUIREMENT_PARAM(ID)
);
CREATE INDEX SYS_IDX_FK_COM_REQUIREMENT_PARAM_CONSTRAINT_PARAMETER_ID_10363 ON PUBLIC.COM_REQUIREMENT_PARAM_CONSTRAINT (PARAMETER_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10360_10361 ON PUBLIC.COM_REQUIREMENT_PARAM_CONSTRAINT (ID);


-- PUBLIC.COM_REQUIREMENT_SELECT_VALUE definition

-- Drop table

-- DROP TABLE PUBLIC.COM_REQUIREMENT_SELECT_VALUE;

CREATE TABLE PUBLIC.COM_REQUIREMENT_SELECT_VALUE (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(255),
	PARAMETER_ID INTEGER,
	CONSTRAINT SYS_PK_10141 PRIMARY KEY (ID),
	CONSTRAINT FK_COM_REQUIREMENT_SELECT_VALUE_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.COM_REQUIREMENT_PARAM(ID)
);
CREATE INDEX SYS_IDX_FK_COM_REQUIREMENT_SELECT_VALUE_PARAMETER_ID_10144 ON PUBLIC.COM_REQUIREMENT_SELECT_VALUE (PARAMETER_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10141_10142 ON PUBLIC.COM_REQUIREMENT_SELECT_VALUE (ID);


-- PUBLIC.COM_UNCERTAINTY_PARAM definition

-- Drop table

-- DROP TABLE PUBLIC.COM_UNCERTAINTY_PARAM;

CREATE TABLE PUBLIC.COM_UNCERTAINTY_PARAM (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(16777216),
	"TYPE" VARCHAR(255),
	MODEL_ID INTEGER,
	PARENT_ID INTEGER,
	"LEVEL" VARCHAR(16) DEFAULT '*',
	REQUIRED VARCHAR(255),
	DEFAULT_VALUE VARCHAR(255),
	CONSTRAINT SYS_PK_10104 PRIMARY KEY (ID),
	CONSTRAINT FK_COM_UNCERTAINTY_PARAM_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES PUBLIC.MODEL(ID)
);
CREATE INDEX SYS_IDX_FK_COM_UNCERTAINTY_PARAM_MODEL_ID_10442 ON PUBLIC.COM_UNCERTAINTY_PARAM (MODEL_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10104_10105 ON PUBLIC.COM_UNCERTAINTY_PARAM (ID);


-- PUBLIC.COM_UNCERTAINTY_SELECT_VALUE definition

-- Drop table

-- DROP TABLE PUBLIC.COM_UNCERTAINTY_SELECT_VALUE;

CREATE TABLE PUBLIC.COM_UNCERTAINTY_SELECT_VALUE (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(16777216),
	PARAMETER_ID INTEGER,
	CONSTRAINT SYS_PK_10116 PRIMARY KEY (ID),
	CONSTRAINT FK_COM_UNCERTAINTY_SELECT_VALUE_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.COM_UNCERTAINTY_PARAM(ID)
);
CREATE INDEX SYS_IDX_FK_COM_UNCERTAINTY_SELECT_VALUE_PARAMETER_ID_10119 ON PUBLIC.COM_UNCERTAINTY_SELECT_VALUE (PARAMETER_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10116_10117 ON PUBLIC.COM_UNCERTAINTY_SELECT_VALUE (ID);


-- PUBLIC.CONFIGURATION_FILE definition

-- Drop table

-- DROP TABLE PUBLIC.CONFIGURATION_FILE;

CREATE TABLE PUBLIC.CONFIGURATION_FILE (
	ID INTEGER NOT NULL IDENTITY,
	DATE_IMPORT TIMESTAMP,
	FEATURE VARCHAR(255),
	"PATH" VARCHAR(255),
	MODEL_ID INTEGER,
	CONSTRAINT SYS_PK_10372 PRIMARY KEY (ID),
	CONSTRAINT FK_CONFIGURATION_FILE_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES PUBLIC.MODEL(ID)
);
CREATE INDEX SYS_IDX_FK_CONFIGURATION_FILE_MODEL_ID_10375 ON PUBLIC.CONFIGURATION_FILE (MODEL_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10372_10373 ON PUBLIC.CONFIGURATION_FILE (ID);


-- PUBLIC.DECISION_PARAM definition

-- Drop table

-- DROP TABLE PUBLIC.DECISION_PARAM;

CREATE TABLE PUBLIC.DECISION_PARAM (
	ID INTEGER NOT NULL IDENTITY,
	IS_REQUIRED BOOLEAN,
	"LEVEL" VARCHAR(16) DEFAULT '*',
	NAME VARCHAR(16777216),
	REQUIRED VARCHAR(255),
	"TYPE" VARCHAR(255),
	MODEL_ID INTEGER,
	PARENT_ID INTEGER,
	DEFAULT_VALUE VARCHAR(255),
	CONSTRAINT SYS_PK_10393 PRIMARY KEY (ID),
	CONSTRAINT FK_DECISION_PARAM_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES PUBLIC.MODEL(ID)
);
CREATE INDEX SYS_IDX_FK_DECISION_PARAM_MODEL_ID_10396 ON PUBLIC.DECISION_PARAM (MODEL_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10393_10394 ON PUBLIC.DECISION_PARAM (ID);


-- PUBLIC.DECISION_PARAM_CONSTRAINT definition

-- Drop table

-- DROP TABLE PUBLIC.DECISION_PARAM_CONSTRAINT;

CREATE TABLE PUBLIC.DECISION_PARAM_CONSTRAINT (
	ID INTEGER NOT NULL IDENTITY,
	RULE VARCHAR(255),
	"TYPE" VARCHAR(255),
	PARAMETER_ID INTEGER,
	CONSTRAINT SYS_PK_10389 PRIMARY KEY (ID),
	CONSTRAINT FK_DECISION_PARAM_CONSTRAINT_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.DECISION_PARAM(ID)
);
CREATE INDEX SYS_IDX_FK_DECISION_PARAM_CONSTRAINT_PARAMETER_ID_10571 ON PUBLIC.DECISION_PARAM_CONSTRAINT (PARAMETER_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10389_10390 ON PUBLIC.DECISION_PARAM_CONSTRAINT (ID);


-- PUBLIC.DECISION_SELECT_VALUE definition

-- Drop table

-- DROP TABLE PUBLIC.DECISION_SELECT_VALUE;

CREATE TABLE PUBLIC.DECISION_SELECT_VALUE (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(255),
	PARAMETER_ID INTEGER,
	CONSTRAINT SYS_PK_10399 PRIMARY KEY (ID),
	CONSTRAINT FK_DECISION_SELECT_VALUE_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.DECISION_PARAM(ID)
);
CREATE INDEX SYS_IDX_FK_DECISION_SELECT_VALUE_PARAMETER_ID_10402 ON PUBLIC.DECISION_SELECT_VALUE (PARAMETER_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10399_10400 ON PUBLIC.DECISION_SELECT_VALUE (ID);


-- PUBLIC.GENERICPARAMETER definition

-- Drop table

-- DROP TABLE PUBLIC.GENERICPARAMETER;

CREATE TABLE PUBLIC.GENERICPARAMETER (
	MODEL_ID INTEGER,
	CONSTRAINT FK_GENERICPARAMETER_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES PUBLIC.MODEL(ID)
);
CREATE INDEX SYS_IDX_FK_GENERICPARAMETER_MODEL_ID_10315 ON PUBLIC.GENERICPARAMETER (MODEL_ID);


-- PUBLIC.INTENDED_PURPOSE definition

-- Drop table

-- DROP TABLE PUBLIC.INTENDED_PURPOSE;

CREATE TABLE PUBLIC.INTENDED_PURPOSE (
	ID INTEGER NOT NULL IDENTITY,
	DESCRIPTION VARCHAR(16777216),
	`REFERENCES` VARCHAR(255),
	CONSTRAINT SYS_PK_11254 PRIMARY KEY (ID),
	CONSTRAINT FK_INTENDED_PURPOSE_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES PUBLIC.MODEL(ID)
);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_11254_10156 ON PUBLIC.INTENDED_PURPOSE (ID);


-- PUBLIC.PCMMELEMENT definition

-- Drop table

-- DROP TABLE PUBLIC.PCMMELEMENT;

CREATE TABLE PUBLIC.PCMMELEMENT (
	ID INTEGER NOT NULL IDENTITY,
	ABBREVIATION VARCHAR(255),
	COLOR VARCHAR(255),
	NAME VARCHAR(255),
	MODEL_ID INTEGER,
	CONSTRAINT SYS_PK_10167 PRIMARY KEY (ID),
	CONSTRAINT FK_PCMMELEMENT_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES PUBLIC.MODEL(ID)
);
CREATE INDEX SYS_IDX_FK_PCMMELEMENT_MODEL_ID_10170 ON PUBLIC.PCMMELEMENT (MODEL_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10167_10168 ON PUBLIC.PCMMELEMENT (ID);


-- PUBLIC.PCMMSUBELEMENT definition

-- Drop table

-- DROP TABLE PUBLIC.PCMMSUBELEMENT;

CREATE TABLE PUBLIC.PCMMSUBELEMENT (
	ID INTEGER NOT NULL IDENTITY,
	CODE VARCHAR(255),
	NAME VARCHAR(255),
	PCMMELEMENT_ID INTEGER,
	CONSTRAINT SYS_PK_10249 PRIMARY KEY (ID),
	CONSTRAINT FK_PCMMSUBELEMENT_PCMMELEMENT_ID FOREIGN KEY (PCMMELEMENT_ID) REFERENCES PUBLIC.PCMMELEMENT(ID)
);
CREATE INDEX SYS_IDX_FK_PCMMSUBELEMENT_PCMMELEMENT_ID_10252 ON PUBLIC.PCMMSUBELEMENT (PCMMELEMENT_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10249_10250 ON PUBLIC.PCMMSUBELEMENT (ID);


-- PUBLIC.PCMM_PLANNING_PARAM definition

-- Drop table

-- DROP TABLE PUBLIC.PCMM_PLANNING_PARAM;

CREATE TABLE PUBLIC.PCMM_PLANNING_PARAM (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(16777216),
	"TYPE" VARCHAR(255),
	MODEL_ID INTEGER,
	PARENT_ID INTEGER,
	"LEVEL" VARCHAR(16) DEFAULT '*',
	REQUIRED VARCHAR(255),
	DEFAULT_VALUE VARCHAR(255),
	CONSTRAINT SYS_PK_10199 PRIMARY KEY (ID),
	CONSTRAINT FK_PCMM_PLANNING_PARAM_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES PUBLIC.MODEL(ID)
);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_PARAM_MODEL_ID_10202 ON PUBLIC.PCMM_PLANNING_PARAM (MODEL_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10199_10200 ON PUBLIC.PCMM_PLANNING_PARAM (ID);


-- PUBLIC.PCMM_PLANNING_PARAM_CONSTRAINT definition

-- Drop table

-- DROP TABLE PUBLIC.PCMM_PLANNING_PARAM_CONSTRAINT;

CREATE TABLE PUBLIC.PCMM_PLANNING_PARAM_CONSTRAINT (
	ID INTEGER NOT NULL IDENTITY,
	RULE VARCHAR(255),
	"TYPE" VARCHAR(255),
	PARAMETER_ID INTEGER,
	CONSTRAINT SYS_PK_10342 PRIMARY KEY (ID),
	CONSTRAINT FK_PCMM_PLANNING_PARAM_CONSTRAINT_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.PCMM_PLANNING_PARAM(ID)
);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_PARAM_CONSTRAINT_PARAMETER_ID_10345 ON PUBLIC.PCMM_PLANNING_PARAM_CONSTRAINT (PARAMETER_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10342_10343 ON PUBLIC.PCMM_PLANNING_PARAM_CONSTRAINT (ID);


-- PUBLIC.PCMM_PLANNING_QUESTION definition

-- Drop table

-- DROP TABLE PUBLIC.PCMM_PLANNING_QUESTION;

CREATE TABLE PUBLIC.PCMM_PLANNING_QUESTION (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(16777216),
	"TYPE" VARCHAR(255),
	PCMMELEMENT_ID INTEGER,
	MODEL_ID INTEGER,
	PARENT_ID INTEGER,
	PCMMSUBELEMENT_ID INTEGER,
	"LEVEL" VARCHAR(16) DEFAULT '*',
	REQUIRED VARCHAR(255),
	DEFAULT_VALUE VARCHAR(255),
	CONSTRAINT SYS_PK_10205 PRIMARY KEY (ID),
	CONSTRAINT FK_PCMM_PLANNING_QUESTION_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES PUBLIC.MODEL(ID),
	CONSTRAINT FK_PCMM_PLANNING_QUESTION_PCMMELEMENT_ID FOREIGN KEY (PCMMELEMENT_ID) REFERENCES PUBLIC.PCMMELEMENT(ID),
	CONSTRAINT FK_PCMM_PLANNING_QUESTION_PCMMSUBELEMENT_ID FOREIGN KEY (PCMMSUBELEMENT_ID) REFERENCES PUBLIC.PCMMSUBELEMENT(ID)
);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_QUESTION_MODEL_ID_10208 ON PUBLIC.PCMM_PLANNING_QUESTION (MODEL_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_QUESTION_PCMMELEMENT_ID_10210 ON PUBLIC.PCMM_PLANNING_QUESTION (PCMMELEMENT_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_QUESTION_PCMMSUBELEMENT_ID_10505 ON PUBLIC.PCMM_PLANNING_QUESTION (PCMMSUBELEMENT_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10205_10206 ON PUBLIC.PCMM_PLANNING_QUESTION (ID);


-- PUBLIC.PCMM_PLANNING_QUESTION_CONSTRAINT definition

-- Drop table

-- DROP TABLE PUBLIC.PCMM_PLANNING_QUESTION_CONSTRAINT;

CREATE TABLE PUBLIC.PCMM_PLANNING_QUESTION_CONSTRAINT (
	ID INTEGER NOT NULL IDENTITY,
	RULE VARCHAR(255),
	"TYPE" VARCHAR(255),
	PARAMETER_ID INTEGER,
	CONSTRAINT SYS_PK_10348 PRIMARY KEY (ID),
	CONSTRAINT FK_PCMM_PLANNING_QUESTION_CONSTRAINT_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.PCMM_PLANNING_QUESTION(ID)
);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_QUESTION_CONSTRAINT_PARAMETER_ID_10351 ON PUBLIC.PCMM_PLANNING_QUESTION_CONSTRAINT (PARAMETER_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10348_10349 ON PUBLIC.PCMM_PLANNING_QUESTION_CONSTRAINT (ID);


-- PUBLIC.PCMM_PLANNING_SELECT_VALUE definition

-- Drop table

-- DROP TABLE PUBLIC.PCMM_PLANNING_SELECT_VALUE;

CREATE TABLE PUBLIC.PCMM_PLANNING_SELECT_VALUE (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(16777216),
	PARAMETER_ID INTEGER,
	CONSTRAINT SYS_PK_10243 PRIMARY KEY (ID),
	CONSTRAINT FK_PCMM_PLANNING_SELECT_VALUE_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.PCMM_PLANNING_PARAM(ID)
);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_SELECT_VALUE_PARAMETER_ID_10246 ON PUBLIC.PCMM_PLANNING_SELECT_VALUE (PARAMETER_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10243_10244 ON PUBLIC.PCMM_PLANNING_SELECT_VALUE (ID);


-- PUBLIC.PIRT_ADEQUACY_LEVEL_GUIDELINE definition

-- Drop table

-- DROP TABLE PUBLIC.PIRT_ADEQUACY_LEVEL_GUIDELINE;

CREATE TABLE PUBLIC.PIRT_ADEQUACY_LEVEL_GUIDELINE (
	ID INTEGER NOT NULL IDENTITY,
	DESCRIPTION VARCHAR(16777216),
	NAME VARCHAR(255),
	PIRT_ADEQUACY_GUIDELINE_ID INTEGER,
	CONSTRAINT SYS_PK_10271 PRIMARY KEY (ID),
	CONSTRAINT PIRTADEQUACYLEVELGUIDELINEPIRTADEQUACYGUIDELINE_ID FOREIGN KEY (PIRT_ADEQUACY_GUIDELINE_ID) REFERENCES PUBLIC.PIRT_ADEQUACY_COLUMN_GUIDELINE(ID)
);
CREATE INDEX SYS_IDX_PIRTADEQUACYLEVELGUIDELINEPIRTADEQUACYGUIDELINE_ID_10274 ON PUBLIC.PIRT_ADEQUACY_LEVEL_GUIDELINE (PIRT_ADEQUACY_GUIDELINE_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10271_10272 ON PUBLIC.PIRT_ADEQUACY_LEVEL_GUIDELINE (ID);


-- PUBLIC.QOI_PLANNING_PARAM definition

-- Drop table

-- DROP TABLE PUBLIC.QOI_PLANNING_PARAM;

CREATE TABLE PUBLIC.QOI_PLANNING_PARAM (
	ID INTEGER NOT NULL IDENTITY,
	"LEVEL" VARCHAR(16) DEFAULT '*',
	NAME VARCHAR(16777216),
	"TYPE" VARCHAR(255),
	MODEL_ID INTEGER,
	PARENT_ID INTEGER,
	REQUIRED VARCHAR(255),
	DEFAULT_VALUE VARCHAR(255),
	CONSTRAINT SYS_PK_10318 PRIMARY KEY (ID),
	CONSTRAINT FK_QOI_PLANNING_PARAM_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES PUBLIC.MODEL(ID)
);
CREATE INDEX SYS_IDX_FK_QOI_PLANNING_PARAM_MODEL_ID_10321 ON PUBLIC.QOI_PLANNING_PARAM (MODEL_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10318_10319 ON PUBLIC.QOI_PLANNING_PARAM (ID);


-- PUBLIC.QOI_PLANNING_PARAM_CONSTRAINT definition

-- Drop table

-- DROP TABLE PUBLIC.QOI_PLANNING_PARAM_CONSTRAINT;

CREATE TABLE PUBLIC.QOI_PLANNING_PARAM_CONSTRAINT (
	ID INTEGER NOT NULL IDENTITY,
	RULE VARCHAR(255),
	"TYPE" VARCHAR(255),
	PARAMETER_ID INTEGER,
	CONSTRAINT SYS_PK_10354 PRIMARY KEY (ID),
	CONSTRAINT FK_QOI_PLANNING_PARAM_CONSTRAINT_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.QOI_PLANNING_PARAM(ID)
);
CREATE INDEX SYS_IDX_FK_QOI_PLANNING_PARAM_CONSTRAINT_PARAMETER_ID_10357 ON PUBLIC.QOI_PLANNING_PARAM_CONSTRAINT (PARAMETER_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10354_10355 ON PUBLIC.QOI_PLANNING_PARAM_CONSTRAINT (ID);


-- PUBLIC.QOI_PLANNING_SELECT_VALUE definition

-- Drop table

-- DROP TABLE PUBLIC.QOI_PLANNING_SELECT_VALUE;

CREATE TABLE PUBLIC.QOI_PLANNING_SELECT_VALUE (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(255),
	PARAMETER_ID INTEGER,
	CONSTRAINT SYS_PK_10324 PRIMARY KEY (ID),
	CONSTRAINT FK_QOI_PLANNING_SELECT_VALUE_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.QOI_PLANNING_PARAM(ID)
);
CREATE INDEX SYS_IDX_FK_QOI_PLANNING_SELECT_VALUE_PARAMETER_ID_10327 ON PUBLIC.QOI_PLANNING_SELECT_VALUE (PARAMETER_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10324_10325 ON PUBLIC.QOI_PLANNING_SELECT_VALUE (ID);


-- PUBLIC.UNCERTAINTY_PARAM_CONSTRAINT definition

-- Drop table

-- DROP TABLE PUBLIC.UNCERTAINTY_PARAM_CONSTRAINT;

CREATE TABLE PUBLIC.UNCERTAINTY_PARAM_CONSTRAINT (
	ID INTEGER NOT NULL IDENTITY,
	RULE VARCHAR(255),
	"TYPE" VARCHAR(255),
	PARAMETER_ID INTEGER,
	CONSTRAINT SYS_PK_10366 PRIMARY KEY (ID),
	CONSTRAINT FK_UNCERTAINTY_PARAM_CONSTRAINT_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.COM_UNCERTAINTY_PARAM(ID)
);
CREATE INDEX SYS_IDX_FK_UNCERTAINTY_PARAM_CONSTRAINT_PARAMETER_ID_10369 ON PUBLIC.UNCERTAINTY_PARAM_CONSTRAINT (PARAMETER_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10366_10367 ON PUBLIC.UNCERTAINTY_PARAM_CONSTRAINT (ID);


-- PUBLIC."USER" definition

-- Drop table

-- DROP TABLE PUBLIC."USER";

CREATE TABLE PUBLIC."USER" (
	ID INTEGER NOT NULL IDENTITY,
	USERID VARCHAR(255),
	CURRENT_ROLE_ID INTEGER,
	CONSTRAINT SYS_PK_10309 PRIMARY KEY (ID),
	CONSTRAINT FK_USER_CURRENT_ROLE_ID FOREIGN KEY (CURRENT_ROLE_ID) REFERENCES PUBLIC."ROLE"(ID)
);
CREATE INDEX SYS_IDX_FK_USER_CURRENT_ROLE_ID_10312 ON PUBLIC."USER" (CURRENT_ROLE_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10309_10310 ON PUBLIC."USER" (ID);


-- PUBLIC.COM_REQUIREMENT definition

-- Drop table

-- DROP TABLE PUBLIC.COM_REQUIREMENT;

CREATE TABLE PUBLIC.COM_REQUIREMENT (
	ID INTEGER NOT NULL IDENTITY,
	CREATION_DATE TIMESTAMP,
	ID_GENERATED VARCHAR(255),
	"LEVEL" INTEGER,
	MODEL_ID INTEGER,
	PARENT_ID INTEGER,
	USER_CREATION_ID INTEGER,
	"STATEMENT" VARCHAR(255),
	CONSTRAINT SYS_PK_10122 PRIMARY KEY (ID),
	CONSTRAINT FK_COM_REQUIREMENT_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES PUBLIC.MODEL(ID),
	CONSTRAINT FK_COM_REQUIREMENT_PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES PUBLIC.COM_REQUIREMENT(ID),
	CONSTRAINT FK_COM_REQUIREMENT_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_COM_REQUIREMENT_MODEL_ID_10451 ON PUBLIC.COM_REQUIREMENT (MODEL_ID);
CREATE INDEX SYS_IDX_FK_COM_REQUIREMENT_PARENT_ID_10125 ON PUBLIC.COM_REQUIREMENT (PARENT_ID);
CREATE INDEX SYS_IDX_FK_COM_REQUIREMENT_USER_CREATION_ID_10454 ON PUBLIC.COM_REQUIREMENT (USER_CREATION_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10122_10123 ON PUBLIC.COM_REQUIREMENT (ID);
CREATE UNIQUE INDEX SYS_IDX_UNQ_COM_REQUIREMENT_3_10127 ON PUBLIC.COM_REQUIREMENT ("STATEMENT");


-- PUBLIC.INTENDED_PURPOSE definition

-- Drop table

-- DROP TABLE PUBLIC.INTENDED_PURPOSE;

CREATE TABLE PUBLIC.INTENDED_PURPOSE (
	ID INTEGER NOT NULL IDENTITY,
	DESCRIPTION VARCHAR(16777216),
	REFERENCE_LINK VARCHAR(16777216),
	DATE_UPDATE TIMESTAMP,
	MODEL_ID INTEGER,
	USER_UPDATE_ID INTEGER,
	CONSTRAINT SYS_PK_10567 PRIMARY KEY (ID),
	CONSTRAINT FK_INTENDED_PURPOSE_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES PUBLIC.MODEL(ID),
	CONSTRAINT FK_INTENDED_PURPOSE_USER_UPDATE_ID FOREIGN KEY (USER_UPDATE_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_INTENDED_PURPOSE_MODEL_ID_10567 ON PUBLIC.INTENDED_PURPOSE (MODEL_ID);
CREATE INDEX SYS_IDX_FK_INTENDED_PURPOSE_USER_UPDATE_ID_10567 ON PUBLIC.INTENDED_PURPOSE (USER_UPDATE_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10567_10294 ON PUBLIC.INTENDED_PURPOSE (ID);


-- PUBLIC.COM_REQUIREMENT_VALUE definition

-- Drop table

-- DROP TABLE PUBLIC.COM_REQUIREMENT_VALUE;

CREATE TABLE PUBLIC.COM_REQUIREMENT_VALUE (
	ID INTEGER NOT NULL IDENTITY,
	DATE_CREATION TIMESTAMP,
	DATE_UPDATE TIMESTAMP,
	"VALUE" VARCHAR(16777216),
	PARAMETER_ID INTEGER,
	REQUIREMENT_ID INTEGER,
	USER_CREATION_ID INTEGER,
	USER_UPDATE_ID INTEGER,
	CONSTRAINT SYS_PK_10133 PRIMARY KEY (ID),
	CONSTRAINT FK_COM_REQUIREMENT_VALUE_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.COM_REQUIREMENT_PARAM(ID),
	CONSTRAINT FK_COM_REQUIREMENT_VALUE_REQUIREMENT_ID FOREIGN KEY (REQUIREMENT_ID) REFERENCES PUBLIC.COM_REQUIREMENT(ID),
	CONSTRAINT FK_COM_REQUIREMENT_VALUE_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID),
	CONSTRAINT FK_COM_REQUIREMENT_VALUE_USER_UPDATE_ID FOREIGN KEY (USER_UPDATE_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_COM_REQUIREMENT_VALUE_PARAMETER_ID_10136 ON PUBLIC.COM_REQUIREMENT_VALUE (PARAMETER_ID);
CREATE INDEX SYS_IDX_FK_COM_REQUIREMENT_VALUE_REQUIREMENT_ID_10138 ON PUBLIC.COM_REQUIREMENT_VALUE (REQUIREMENT_ID);
CREATE INDEX SYS_IDX_FK_COM_REQUIREMENT_VALUE_USER_CREATION_ID_10460 ON PUBLIC.COM_REQUIREMENT_VALUE (USER_CREATION_ID);
CREATE INDEX SYS_IDX_FK_COM_REQUIREMENT_VALUE_USER_UPDATE_ID_10463 ON PUBLIC.COM_REQUIREMENT_VALUE (USER_UPDATE_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10133_10134 ON PUBLIC.COM_REQUIREMENT_VALUE (ID);


-- PUBLIC.COM_UNCERTAINTY_GROUP definition

-- Drop table

-- DROP TABLE PUBLIC.COM_UNCERTAINTY_GROUP;

CREATE TABLE PUBLIC.COM_UNCERTAINTY_GROUP (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(255),
	MODEL_ID INTEGER,
	USER_CREATION_ID INTEGER,
	CONSTRAINT SYS_PK_10100 PRIMARY KEY (ID),
	CONSTRAINT FK_COM_UNCERTAINTY_GROUP_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES PUBLIC.MODEL(ID),
	CONSTRAINT FK_COM_UNCERTAINTY_GROUP_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_COM_UNCERTAINTY_GROUP_MODEL_ID_10436 ON PUBLIC.COM_UNCERTAINTY_GROUP (MODEL_ID);
CREATE INDEX SYS_IDX_FK_COM_UNCERTAINTY_GROUP_USER_CREATION_ID_10439 ON PUBLIC.COM_UNCERTAINTY_GROUP (USER_CREATION_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10100_10101 ON PUBLIC.COM_UNCERTAINTY_GROUP (ID);


-- PUBLIC.DECISION definition

-- Drop table

-- DROP TABLE PUBLIC.DECISION;

CREATE TABLE PUBLIC.DECISION (
	ID INTEGER NOT NULL IDENTITY,
	CREATION_DATE TIMESTAMP,
	ID_GENERATED VARCHAR(255),
	MODEL_ID INTEGER,
	PARENT_ID INTEGER,
	USER_CREATION_ID INTEGER,
	TITLE VARCHAR(255),
	CONSTRAINT SYS_PK_10378 PRIMARY KEY (ID),
	CONSTRAINT FK_DECISION_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES PUBLIC.MODEL(ID),
	CONSTRAINT FK_DECISION_PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES PUBLIC.DECISION(ID),
	CONSTRAINT FK_DECISION_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_DECISION_MODEL_ID_10385 ON PUBLIC.DECISION (MODEL_ID);
CREATE INDEX SYS_IDX_FK_DECISION_PARENT_ID_10383 ON PUBLIC.DECISION (PARENT_ID);
CREATE INDEX SYS_IDX_FK_DECISION_USER_CREATION_ID_10381 ON PUBLIC.DECISION (USER_CREATION_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10378_10379 ON PUBLIC.DECISION (ID);
CREATE UNIQUE INDEX SYS_IDX_UNQ_DECISION_3_10387 ON PUBLIC.DECISION (TITLE);


-- PUBLIC.DECISION_VALUE definition

-- Drop table

-- DROP TABLE PUBLIC.DECISION_VALUE;

CREATE TABLE PUBLIC.DECISION_VALUE (
	ID INTEGER NOT NULL IDENTITY,
	DATE_CREATION TIMESTAMP,
	DATE_UPDATE TIMESTAMP,
	"VALUE" VARCHAR(16777216),
	DECISION_ID INTEGER,
	PARAMETER_ID INTEGER,
	USER_CREATION_ID INTEGER,
	USER_UPDATE_ID INTEGER,
	CONSTRAINT SYS_PK_10405 PRIMARY KEY (ID),
	CONSTRAINT FK_DECISION_VALUE_DECISION_ID FOREIGN KEY (DECISION_ID) REFERENCES PUBLIC.DECISION(ID),
	CONSTRAINT FK_DECISION_VALUE_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.DECISION_PARAM(ID),
	CONSTRAINT FK_DECISION_VALUE_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID),
	CONSTRAINT FK_DECISION_VALUE_USER_UPDATE_ID FOREIGN KEY (USER_UPDATE_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_DECISION_VALUE_DECISION_ID_10412 ON PUBLIC.DECISION_VALUE (DECISION_ID);
CREATE INDEX SYS_IDX_FK_DECISION_VALUE_PARAMETER_ID_10414 ON PUBLIC.DECISION_VALUE (PARAMETER_ID);
CREATE INDEX SYS_IDX_FK_DECISION_VALUE_USER_CREATION_ID_10408 ON PUBLIC.DECISION_VALUE (USER_CREATION_ID);
CREATE INDEX SYS_IDX_FK_DECISION_VALUE_USER_UPDATE_ID_10410 ON PUBLIC.DECISION_VALUE (USER_UPDATE_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10405_10406 ON PUBLIC.DECISION_VALUE (ID);


-- PUBLIC.PCMMLEVEL definition

-- Drop table

-- DROP TABLE PUBLIC.PCMMLEVEL;

CREATE TABLE PUBLIC.PCMMLEVEL (
	ID INTEGER NOT NULL IDENTITY,
	CODE INTEGER,
	NAME VARCHAR(255),
	PCMMELEMENT_ID INTEGER,
	PCMMSUBELEMENT_ID INTEGER,
	CONSTRAINT SYS_PK_10179 PRIMARY KEY (ID),
	CONSTRAINT FK_PCMMLEVEL_PCMMELEMENT_ID FOREIGN KEY (PCMMELEMENT_ID) REFERENCES PUBLIC.PCMMELEMENT(ID),
	CONSTRAINT FK_PCMMLEVEL_PCMMSUBELEMENT_ID FOREIGN KEY (PCMMSUBELEMENT_ID) REFERENCES PUBLIC.PCMMSUBELEMENT(ID)
);
CREATE INDEX SYS_IDX_FK_PCMMLEVEL_PCMMELEMENT_ID_10182 ON PUBLIC.PCMMLEVEL (PCMMELEMENT_ID);
CREATE INDEX SYS_IDX_FK_PCMMLEVEL_PCMMSUBELEMENT_ID_10502 ON PUBLIC.PCMMLEVEL (PCMMSUBELEMENT_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10179_10180 ON PUBLIC.PCMMLEVEL (ID);


-- PUBLIC.PCMMLEVELDESC definition

-- Drop table

-- DROP TABLE PUBLIC.PCMMLEVELDESC;

CREATE TABLE PUBLIC.PCMMLEVELDESC (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(255),
	"VALUE" VARCHAR(1500),
	PCMMLEVEL_ID INTEGER,
	CONSTRAINT SYS_PK_10189 PRIMARY KEY (ID),
	CONSTRAINT FK_PCMMLEVELDESC_PCMMLEVEL_ID FOREIGN KEY (PCMMLEVEL_ID) REFERENCES PUBLIC.PCMMLEVEL(ID)
);
CREATE INDEX SYS_IDX_FK_PCMMLEVELDESC_PCMMLEVEL_ID_10192 ON PUBLIC.PCMMLEVELDESC (PCMMLEVEL_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10189_10190 ON PUBLIC.PCMMLEVELDESC (ID);


-- PUBLIC.QOI definition

-- Drop table

-- DROP TABLE PUBLIC.QOI;

CREATE TABLE PUBLIC.QOI (
	ID INTEGER NOT NULL IDENTITY,
	CREATION_DATE TIMESTAMP,
	DESCRIPTION VARCHAR(16777216),
	NAME VARCHAR(255),
	TAG VARCHAR(255),
	TAG_DATE TIMESTAMP,
	TAG_DESCRIPTION VARCHAR(255),
	MODEL_ID INTEGER,
	PARENT_ID INTEGER,
	TAG_USER_CREATION_ID INTEGER,
	UPDATE_DATE TIMESTAMP,
	USER_CREATION_ID INTEGER,
	USER_UPDATE_ID INTEGER,
	CONSTRAINT SYS_PK_10293 PRIMARY KEY (ID),
	CONSTRAINT FK_QOI_MODEL_ID FOREIGN KEY (MODEL_ID) REFERENCES PUBLIC.MODEL(ID),
	CONSTRAINT FK_QOI_PARENT_ID FOREIGN KEY (PARENT_ID) REFERENCES PUBLIC.QOI(ID),
	CONSTRAINT FK_QOI_TAG_USER_CREATION_ID FOREIGN KEY (TAG_USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID),
	CONSTRAINT FK_QOI_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_QOI_MODEL_ID_10298 ON PUBLIC.QOI (MODEL_ID);
CREATE INDEX SYS_IDX_FK_QOI_PARENT_ID_10296 ON PUBLIC.QOI (PARENT_ID);
CREATE INDEX SYS_IDX_FK_QOI_TAG_USER_CREATION_ID_10562 ON PUBLIC.QOI (TAG_USER_CREATION_ID);
CREATE INDEX SYS_IDX_FK_QOI_USER_CREATION_ID_10565 ON PUBLIC.QOI (USER_CREATION_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10293_10294 ON PUBLIC.QOI (ID);


-- PUBLIC.QOIHEADER definition

-- Drop table

-- DROP TABLE PUBLIC.QOIHEADER;

CREATE TABLE PUBLIC.QOIHEADER (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(255),
	"VALUE" VARCHAR(255),
	QOI_ID INTEGER,
	CREATION_DATE TIMESTAMP,
	UPDATE_DATE TIMESTAMP,
	USER_CREATION_ID INTEGER,
	USER_UPDATE_ID INTEGER,
	CONSTRAINT SYS_PK_10289 PRIMARY KEY (ID),
	CONSTRAINT FK_QOIHEADER_QOI_ID FOREIGN KEY (QOI_ID) REFERENCES PUBLIC.QOI(ID),
	CONSTRAINT FK_QOIHEADER_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID),
	CONSTRAINT FK_QOIHEADER_USER_UPDATE_ID FOREIGN KEY (USER_UPDATE_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_QOIHEADER_QOI_ID_10553 ON PUBLIC.QOIHEADER (QOI_ID);
CREATE INDEX SYS_IDX_FK_QOIHEADER_USER_CREATION_ID_10556 ON PUBLIC.QOIHEADER (USER_CREATION_ID);
CREATE INDEX SYS_IDX_FK_QOIHEADER_USER_UPDATE_ID_10559 ON PUBLIC.QOIHEADER (USER_UPDATE_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10289_10290 ON PUBLIC.QOIHEADER (ID);


-- PUBLIC.QOI_PLANNING_VALUE definition

-- Drop table

-- DROP TABLE PUBLIC.QOI_PLANNING_VALUE;

CREATE TABLE PUBLIC.QOI_PLANNING_VALUE (
	ID INTEGER NOT NULL IDENTITY,
	DATE_CREATION TIMESTAMP,
	DATE_UPDATE TIMESTAMP,
	"VALUE" VARCHAR(16777216),
	PARAMETER_ID INTEGER,
	REQUIREMENT_ID INTEGER,
	USER_CREATION_ID INTEGER,
	USER_UPDATE_ID INTEGER,
	QOI_ID INTEGER,
	CONSTRAINT SYS_PK_10330 PRIMARY KEY (ID),
	CONSTRAINT FK_QOI_PLANNING_VALUE_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.QOI_PLANNING_PARAM(ID),
	CONSTRAINT FK_QOI_PLANNING_VALUE_REQUIREMENT_ID FOREIGN KEY (REQUIREMENT_ID) REFERENCES PUBLIC.QOI(ID),
	CONSTRAINT FK_QOI_PLANNING_VALUE_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID),
	CONSTRAINT FK_QOI_PLANNING_VALUE_USER_UPDATE_ID FOREIGN KEY (USER_UPDATE_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_QOI_PLANNING_VALUE_PARAMETER_ID_10333 ON PUBLIC.QOI_PLANNING_VALUE (PARAMETER_ID);
CREATE INDEX SYS_IDX_FK_QOI_PLANNING_VALUE_REQUIREMENT_ID_10337 ON PUBLIC.QOI_PLANNING_VALUE (REQUIREMENT_ID);
CREATE INDEX SYS_IDX_FK_QOI_PLANNING_VALUE_USER_CREATION_ID_10335 ON PUBLIC.QOI_PLANNING_VALUE (USER_CREATION_ID);
CREATE INDEX SYS_IDX_FK_QOI_PLANNING_VALUE_USER_UPDATE_ID_10339 ON PUBLIC.QOI_PLANNING_VALUE (USER_UPDATE_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10330_10331 ON PUBLIC.QOI_PLANNING_VALUE (ID);


-- PUBLIC.TAG definition

-- Drop table

-- DROP TABLE PUBLIC.TAG;

CREATE TABLE PUBLIC.TAG (
	ID INTEGER NOT NULL IDENTITY,
	DATETAG TIMESTAMP,
	DESCRIPTION VARCHAR(255),
	NAME VARCHAR(255),
	USER_CREATION_ID INTEGER,
	CONSTRAINT SYS_PK_10305 PRIMARY KEY (ID),
	CONSTRAINT FK_TAG_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_TAG_USER_CREATION_ID_10568 ON PUBLIC.TAG (USER_CREATION_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10305_10306 ON PUBLIC.TAG (ID);


-- PUBLIC.ARG_PARAMETERS definition

-- Drop table

-- DROP TABLE PUBLIC.ARG_PARAMETERS;

CREATE TABLE PUBLIC.ARG_PARAMETERS (
	ID INTEGER NOT NULL IDENTITY,
	BACKEND_TYPE VARCHAR(255),
	FILENAME VARCHAR(255),
	"NUMBER" VARCHAR(255),
	"OUTPUT" VARCHAR(16777216),
	PARAMETERS_FILE_PATH VARCHAR(16777216),
	REPORT_TYPE VARCHAR(255),
	STRUCTURE_FILE_PATH VARCHAR(16777216),
	TITLE VARCHAR(255),
	AUTHOR VARCHAR(255),
	PCMM_ASSESSMENT_ENABLED BOOLEAN,
	PCMM_ENABLED BOOLEAN,
	PCMM_EVIDENCE_ENABLED BOOLEAN,
	PCMM_PLANNING_ENABLED BOOLEAN,
	PIRT_ENABLED BOOLEAN,
	PLANNING_DECISION_ENABLED BOOLEAN,
	PLANNING_ENABLED BOOLEAN,
	PLANNING_INTENDEDPURPOSE_ENABLED BOOLEAN,
	PLANNING_SYSREQ_ENABLED BOOLEAN,
	PLANNING_UNCERTAINTY_ENABLED BOOLEAN,
	PCMM_TAG INTEGER,
	ARG_EXECUTABLE_PATH VARCHAR(16777216),
	ARG_PREEXECUTION_SCRIPT VARCHAR(16777216),
	PYTHON_EXECUTABLE_PATH VARCHAR(16777216),
	USE_ARG_LOCAL_CONF BOOLEAN,
	CUSTOM_ENDING_FILE_PATH VARCHAR(16777216),
	CUSTOM_ENDING_ENABLED BOOLEAN,
	CONSTRAINT SYS_PK_10092 PRIMARY KEY (ID),
	CONSTRAINT FK_ARG_PARAMETERS_PCMM_TAG FOREIGN KEY (PCMM_TAG) REFERENCES PUBLIC.TAG(ID)
);
CREATE INDEX SYS_IDX_FK_ARG_PARAMETERS_PCMM_TAG_10427 ON PUBLIC.ARG_PARAMETERS (PCMM_TAG);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10092_10093 ON PUBLIC.ARG_PARAMETERS (ID);


-- PUBLIC.ARG_PARAMETERS_QOI_OPTIONS definition

-- Drop table

-- DROP TABLE PUBLIC.ARG_PARAMETERS_QOI_OPTIONS;

CREATE TABLE PUBLIC.ARG_PARAMETERS_QOI_OPTIONS (
	ID INTEGER NOT NULL IDENTITY,
	ENABLED BOOLEAN,
	ARG_PARAM_ID INTEGER,
	QOI_ID INTEGER,
	QOI_TAG_ID INTEGER,
	CONSTRAINT SYS_PK_10417 PRIMARY KEY (ID),
	CONSTRAINT FK_ARG_PARAMETERS_QOI_OPTIONS_ARG_PARAM_ID FOREIGN KEY (ARG_PARAM_ID) REFERENCES PUBLIC.ARG_PARAMETERS(ID),
	CONSTRAINT FK_ARG_PARAMETERS_QOI_OPTIONS_QOI_ID FOREIGN KEY (QOI_ID) REFERENCES PUBLIC.QOI(ID),
	CONSTRAINT FK_ARG_PARAMETERS_QOI_OPTIONS_QOI_TAG_ID FOREIGN KEY (QOI_TAG_ID) REFERENCES PUBLIC.QOI(ID)
);
CREATE INDEX SYS_IDX_FK_ARG_PARAMETERS_QOI_OPTIONS_ARG_PARAM_ID_10424 ON PUBLIC.ARG_PARAMETERS_QOI_OPTIONS (ARG_PARAM_ID);
CREATE INDEX SYS_IDX_FK_ARG_PARAMETERS_QOI_OPTIONS_QOI_ID_10420 ON PUBLIC.ARG_PARAMETERS_QOI_OPTIONS (QOI_ID);
CREATE INDEX SYS_IDX_FK_ARG_PARAMETERS_QOI_OPTIONS_QOI_TAG_ID_10422 ON PUBLIC.ARG_PARAMETERS_QOI_OPTIONS (QOI_TAG_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10417_10418 ON PUBLIC.ARG_PARAMETERS_QOI_OPTIONS (ID);


-- PUBLIC.COM_UNCERTAINTY definition

-- Drop table

-- DROP TABLE PUBLIC.COM_UNCERTAINTY;

CREATE TABLE PUBLIC.COM_UNCERTAINTY (
	ID INTEGER NOT NULL IDENTITY,
	GROUP_ID INTEGER,
	USER_CREATION_ID INTEGER,
	CONSTRAINT SYS_PK_10096 PRIMARY KEY (ID),
	CONSTRAINT FK_COM_UNCERTAINTY_GROUP_ID FOREIGN KEY (GROUP_ID) REFERENCES PUBLIC.COM_UNCERTAINTY_GROUP(ID),
	CONSTRAINT FK_COM_UNCERTAINTY_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_COM_UNCERTAINTY_GROUP_ID_10430 ON PUBLIC.COM_UNCERTAINTY (GROUP_ID);
CREATE INDEX SYS_IDX_FK_COM_UNCERTAINTY_USER_CREATION_ID_10433 ON PUBLIC.COM_UNCERTAINTY (USER_CREATION_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10096_10097 ON PUBLIC.COM_UNCERTAINTY (ID);


-- PUBLIC.COM_UNCERTAINTY_VALUE definition

-- Drop table

-- DROP TABLE PUBLIC.COM_UNCERTAINTY_VALUE;

CREATE TABLE PUBLIC.COM_UNCERTAINTY_VALUE (
	ID INTEGER NOT NULL IDENTITY,
	DATE_CREATION TIMESTAMP,
	DATE_UPDATE TIMESTAMP,
	"VALUE" VARCHAR(16777216),
	PARAMETER_ID INTEGER,
	UNCERTAINTY_ID INTEGER,
	USER_CREATION_ID INTEGER,
	USER_UPDATE_ID INTEGER,
	CONSTRAINT SYS_PK_10108 PRIMARY KEY (ID),
	CONSTRAINT FK_COM_UNCERTAINTY_VALUE_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.COM_UNCERTAINTY_PARAM(ID),
	CONSTRAINT FK_COM_UNCERTAINTY_VALUE_UNCERTAINTY_ID FOREIGN KEY (UNCERTAINTY_ID) REFERENCES PUBLIC.COM_UNCERTAINTY(ID),
	CONSTRAINT FK_COM_UNCERTAINTY_VALUE_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID),
	CONSTRAINT FK_COM_UNCERTAINTY_VALUE_USER_UPDATE_ID FOREIGN KEY (USER_UPDATE_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_COM_UNCERTAINTY_VALUE_PARAMETER_ID_10111 ON PUBLIC.COM_UNCERTAINTY_VALUE (PARAMETER_ID);
CREATE INDEX SYS_IDX_FK_COM_UNCERTAINTY_VALUE_UNCERTAINTY_ID_10113 ON PUBLIC.COM_UNCERTAINTY_VALUE (UNCERTAINTY_ID);
CREATE INDEX SYS_IDX_FK_COM_UNCERTAINTY_VALUE_USER_CREATION_ID_10445 ON PUBLIC.COM_UNCERTAINTY_VALUE (USER_CREATION_ID);
CREATE INDEX SYS_IDX_FK_COM_UNCERTAINTY_VALUE_USER_UPDATE_ID_10448 ON PUBLIC.COM_UNCERTAINTY_VALUE (USER_UPDATE_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10108_10109 ON PUBLIC.COM_UNCERTAINTY_VALUE (ID);


-- PUBLIC.PCMMASSESSMENT definition

-- Drop table

-- DROP TABLE PUBLIC.PCMMASSESSMENT;

CREATE TABLE PUBLIC.PCMMASSESSMENT (
	ID INTEGER NOT NULL IDENTITY,
	COMMENT VARCHAR(16777216),
	DATE_CREATION TIMESTAMP,
	DATE_UPDATE TIMESTAMP,
	PCMMELEMENT_ID INTEGER,
	PCMMLEVEL_ID INTEGER,
	ROLE_CREATION_ID INTEGER,
	PCMMSUBELEMENT_ID INTEGER,
	TAG_ID INTEGER,
	USER_CREATION_ID INTEGER,
	CONSTRAINT SYS_PK_10163 PRIMARY KEY (ID),
	CONSTRAINT FK_PCMMASSESSMENT_PCMMELEMENT_ID FOREIGN KEY (PCMMELEMENT_ID) REFERENCES PUBLIC.PCMMELEMENT(ID),
	CONSTRAINT FK_PCMMASSESSMENT_PCMMLEVEL_ID FOREIGN KEY (PCMMLEVEL_ID) REFERENCES PUBLIC.PCMMLEVEL(ID),
	CONSTRAINT FK_PCMMASSESSMENT_PCMMSUBELEMENT_ID FOREIGN KEY (PCMMSUBELEMENT_ID) REFERENCES PUBLIC.PCMMSUBELEMENT(ID),
	CONSTRAINT FK_PCMMASSESSMENT_ROLE_CREATION_ID FOREIGN KEY (ROLE_CREATION_ID) REFERENCES PUBLIC."ROLE"(ID),
	CONSTRAINT FK_PCMMASSESSMENT_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES PUBLIC.TAG(ID),
	CONSTRAINT FK_PCMMASSESSMENT_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_PCMMASSESSMENT_PCMMELEMENT_ID_10478 ON PUBLIC.PCMMASSESSMENT (PCMMELEMENT_ID);
CREATE INDEX SYS_IDX_FK_PCMMASSESSMENT_PCMMLEVEL_ID_10484 ON PUBLIC.PCMMASSESSMENT (PCMMLEVEL_ID);
CREATE INDEX SYS_IDX_FK_PCMMASSESSMENT_PCMMSUBELEMENT_ID_10487 ON PUBLIC.PCMMASSESSMENT (PCMMSUBELEMENT_ID);
CREATE INDEX SYS_IDX_FK_PCMMASSESSMENT_ROLE_CREATION_ID_10472 ON PUBLIC.PCMMASSESSMENT (ROLE_CREATION_ID);
CREATE INDEX SYS_IDX_FK_PCMMASSESSMENT_TAG_ID_10475 ON PUBLIC.PCMMASSESSMENT (TAG_ID);
CREATE INDEX SYS_IDX_FK_PCMMASSESSMENT_USER_CREATION_ID_10481 ON PUBLIC.PCMMASSESSMENT (USER_CREATION_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10163_10164 ON PUBLIC.PCMMASSESSMENT (ID);


-- PUBLIC.PCMMEVIDENCE definition

-- Drop table

-- DROP TABLE PUBLIC.PCMMEVIDENCE;

CREATE TABLE PUBLIC.PCMMEVIDENCE (
	ID INTEGER NOT NULL IDENTITY,
	DATE_CREATION TIMESTAMP,
	DATE_FILE TIMESTAMP,
	DATE_UPDATE TIMESTAMP,
	DESCRIPTION VARCHAR(16777216),
	NAME VARCHAR(255),
	PCMMELEMENT_ID INTEGER,
	ROLE_CREATION_ID INTEGER,
	PCMMSUBELEMENT_ID INTEGER,
	TAG_ID INTEGER,
	USER_CREATION_ID INTEGER,
	"SECTION" VARCHAR(255),
	"VALUE" VARCHAR(255),
	CONSTRAINT SYS_PK_10173 PRIMARY KEY (ID),
	CONSTRAINT FK_PCMMEVIDENCE_PCMMELEMENT_ID FOREIGN KEY (PCMMELEMENT_ID) REFERENCES PUBLIC.PCMMELEMENT(ID),
	CONSTRAINT FK_PCMMEVIDENCE_PCMMSUBELEMENT_ID FOREIGN KEY (PCMMSUBELEMENT_ID) REFERENCES PUBLIC.PCMMSUBELEMENT(ID),
	CONSTRAINT FK_PCMMEVIDENCE_ROLE_CREATION_ID FOREIGN KEY (ROLE_CREATION_ID) REFERENCES PUBLIC."ROLE"(ID),
	CONSTRAINT FK_PCMMEVIDENCE_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES PUBLIC.TAG(ID),
	CONSTRAINT FK_PCMMEVIDENCE_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_PCMMEVIDENCE_PCMMELEMENT_ID_10176 ON PUBLIC.PCMMEVIDENCE (PCMMELEMENT_ID);
CREATE INDEX SYS_IDX_FK_PCMMEVIDENCE_PCMMSUBELEMENT_ID_10490 ON PUBLIC.PCMMEVIDENCE (PCMMSUBELEMENT_ID);
CREATE INDEX SYS_IDX_FK_PCMMEVIDENCE_ROLE_CREATION_ID_10493 ON PUBLIC.PCMMEVIDENCE (ROLE_CREATION_ID);
CREATE INDEX SYS_IDX_FK_PCMMEVIDENCE_TAG_ID_10496 ON PUBLIC.PCMMEVIDENCE (TAG_ID);
CREATE INDEX SYS_IDX_FK_PCMMEVIDENCE_USER_CREATION_ID_10499 ON PUBLIC.PCMMEVIDENCE (USER_CREATION_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10173_10174 ON PUBLIC.PCMMEVIDENCE (ID);


-- PUBLIC.PCMM_PLANNING_QUESTION_VALUE definition

-- Drop table

-- DROP TABLE PUBLIC.PCMM_PLANNING_QUESTION_VALUE;

CREATE TABLE PUBLIC.PCMM_PLANNING_QUESTION_VALUE (
	ID INTEGER NOT NULL IDENTITY,
	DATE_CREATION TIMESTAMP,
	DATE_UPDATE TIMESTAMP,
	"VALUE" VARCHAR(16777216),
	PARAMETER_ID INTEGER,
	TAG_ID INTEGER,
	USER_CREATION_ID INTEGER,
	USER_UPDATE_ID INTEGER,
	CONSTRAINT SYS_PK_10213 PRIMARY KEY (ID),
	CONSTRAINT FK_PCMM_PLANNING_QUESTION_VALUE_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.PCMM_PLANNING_QUESTION(ID),
	CONSTRAINT FK_PCMM_PLANNING_QUESTION_VALUE_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES PUBLIC.TAG(ID),
	CONSTRAINT FK_PCMM_PLANNING_QUESTION_VALUE_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID),
	CONSTRAINT FK_PCMM_PLANNING_QUESTION_VALUE_USER_UPDATE_ID FOREIGN KEY (USER_UPDATE_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_QUESTION_VALUE_PARAMETER_ID_10216 ON PUBLIC.PCMM_PLANNING_QUESTION_VALUE (PARAMETER_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_QUESTION_VALUE_TAG_ID_10508 ON PUBLIC.PCMM_PLANNING_QUESTION_VALUE (TAG_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_QUESTION_VALUE_USER_CREATION_ID_10514 ON PUBLIC.PCMM_PLANNING_QUESTION_VALUE (USER_CREATION_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_QUESTION_VALUE_USER_UPDATE_ID_10511 ON PUBLIC.PCMM_PLANNING_QUESTION_VALUE (USER_UPDATE_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10213_10214 ON PUBLIC.PCMM_PLANNING_QUESTION_VALUE (ID);


-- PUBLIC.PCMM_PLANNING_TABLE_ITEM definition

-- Drop table

-- DROP TABLE PUBLIC.PCMM_PLANNING_TABLE_ITEM;

CREATE TABLE PUBLIC.PCMM_PLANNING_TABLE_ITEM (
	ID INTEGER NOT NULL IDENTITY,
	DATE_CREATION TIMESTAMP,
	DATE_UPDATE TIMESTAMP,
	"VALUE" VARCHAR(16777216),
	PCMMELEMENT_ID INTEGER,
	PARAMETER_ID INTEGER,
	PCMMSUBELEMENT_ID INTEGER,
	TAG_ID INTEGER,
	USER_CREATION_ID INTEGER,
	USER_UPDATE_ID INTEGER,
	CONSTRAINT SYS_PK_10219 PRIMARY KEY (ID),
	CONSTRAINT FK_PCMM_PLANNING_TABLE_ITEM_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.PCMM_PLANNING_PARAM(ID),
	CONSTRAINT FK_PCMM_PLANNING_TABLE_ITEM_PCMMELEMENT_ID FOREIGN KEY (PCMMELEMENT_ID) REFERENCES PUBLIC.PCMMELEMENT(ID),
	CONSTRAINT FK_PCMM_PLANNING_TABLE_ITEM_PCMMSUBELEMENT_ID FOREIGN KEY (PCMMSUBELEMENT_ID) REFERENCES PUBLIC.PCMMSUBELEMENT(ID),
	CONSTRAINT FK_PCMM_PLANNING_TABLE_ITEM_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES PUBLIC.TAG(ID),
	CONSTRAINT FK_PCMM_PLANNING_TABLE_ITEM_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID),
	CONSTRAINT FK_PCMM_PLANNING_TABLE_ITEM_USER_UPDATE_ID FOREIGN KEY (USER_UPDATE_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_TABLE_ITEM_PARAMETER_ID_10224 ON PUBLIC.PCMM_PLANNING_TABLE_ITEM (PARAMETER_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_TABLE_ITEM_PCMMELEMENT_ID_10222 ON PUBLIC.PCMM_PLANNING_TABLE_ITEM (PCMMELEMENT_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_TABLE_ITEM_PCMMSUBELEMENT_ID_10520 ON PUBLIC.PCMM_PLANNING_TABLE_ITEM (PCMMSUBELEMENT_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_TABLE_ITEM_TAG_ID_10517 ON PUBLIC.PCMM_PLANNING_TABLE_ITEM (TAG_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_TABLE_ITEM_USER_CREATION_ID_10523 ON PUBLIC.PCMM_PLANNING_TABLE_ITEM (USER_CREATION_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_TABLE_ITEM_USER_UPDATE_ID_10526 ON PUBLIC.PCMM_PLANNING_TABLE_ITEM (USER_UPDATE_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10219_10220 ON PUBLIC.PCMM_PLANNING_TABLE_ITEM (ID);


-- PUBLIC.PCMM_PLANNING_TABLE_VALUE definition

-- Drop table

-- DROP TABLE PUBLIC.PCMM_PLANNING_TABLE_VALUE;

CREATE TABLE PUBLIC.PCMM_PLANNING_TABLE_VALUE (
	ID INTEGER NOT NULL IDENTITY,
	DATE_CREATION TIMESTAMP,
	DATE_UPDATE TIMESTAMP,
	"VALUE" VARCHAR(16777216),
	ITEM_ID INTEGER,
	PARAMETER_ID INTEGER,
	USER_CREATION_ID INTEGER,
	USER_UPDATE_ID INTEGER,
	CONSTRAINT SYS_PK_10227 PRIMARY KEY (ID),
	CONSTRAINT FK_PCMM_PLANNING_TABLE_VALUE_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES PUBLIC.PCMM_PLANNING_TABLE_ITEM(ID),
	CONSTRAINT FK_PCMM_PLANNING_TABLE_VALUE_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.PCMM_PLANNING_PARAM(ID),
	CONSTRAINT FK_PCMM_PLANNING_TABLE_VALUE_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID),
	CONSTRAINT FK_PCMM_PLANNING_TABLE_VALUE_USER_UPDATE_ID FOREIGN KEY (USER_UPDATE_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_TABLE_VALUE_ITEM_ID_10230 ON PUBLIC.PCMM_PLANNING_TABLE_VALUE (ITEM_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_TABLE_VALUE_PARAMETER_ID_10232 ON PUBLIC.PCMM_PLANNING_TABLE_VALUE (PARAMETER_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_TABLE_VALUE_USER_CREATION_ID_10529 ON PUBLIC.PCMM_PLANNING_TABLE_VALUE (USER_CREATION_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_TABLE_VALUE_USER_UPDATE_ID_10532 ON PUBLIC.PCMM_PLANNING_TABLE_VALUE (USER_UPDATE_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10227_10228 ON PUBLIC.PCMM_PLANNING_TABLE_VALUE (ID);


-- PUBLIC.PCMM_PLANNING_VALUE definition

-- Drop table

-- DROP TABLE PUBLIC.PCMM_PLANNING_VALUE;

CREATE TABLE PUBLIC.PCMM_PLANNING_VALUE (
	ID INTEGER NOT NULL IDENTITY,
	DATE_CREATION TIMESTAMP,
	DATE_UPDATE TIMESTAMP,
	"VALUE" VARCHAR(16777216),
	PCMMELEMENT_ID INTEGER,
	PARAMETER_ID INTEGER,
	PCMMSUBELEMENT_ID INTEGER,
	TAG_ID INTEGER,
	USER_CREATION_ID INTEGER,
	USER_UPDATE_ID INTEGER,
	CONSTRAINT SYS_PK_10235 PRIMARY KEY (ID),
	CONSTRAINT FK_PCMM_PLANNING_VALUE_PARAMETER_ID FOREIGN KEY (PARAMETER_ID) REFERENCES PUBLIC.PCMM_PLANNING_PARAM(ID),
	CONSTRAINT FK_PCMM_PLANNING_VALUE_PCMMELEMENT_ID FOREIGN KEY (PCMMELEMENT_ID) REFERENCES PUBLIC.PCMMELEMENT(ID),
	CONSTRAINT FK_PCMM_PLANNING_VALUE_PCMMSUBELEMENT_ID FOREIGN KEY (PCMMSUBELEMENT_ID) REFERENCES PUBLIC.PCMMSUBELEMENT(ID),
	CONSTRAINT FK_PCMM_PLANNING_VALUE_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES PUBLIC.TAG(ID),
	CONSTRAINT FK_PCMM_PLANNING_VALUE_USER_CREATION_ID FOREIGN KEY (USER_CREATION_ID) REFERENCES PUBLIC."USER"(ID),
	CONSTRAINT FK_PCMM_PLANNING_VALUE_USER_UPDATE_ID FOREIGN KEY (USER_UPDATE_ID) REFERENCES PUBLIC."USER"(ID)
);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_VALUE_PARAMETER_ID_10240 ON PUBLIC.PCMM_PLANNING_VALUE (PARAMETER_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_VALUE_PCMMELEMENT_ID_10238 ON PUBLIC.PCMM_PLANNING_VALUE (PCMMELEMENT_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_VALUE_PCMMSUBELEMENT_ID_10538 ON PUBLIC.PCMM_PLANNING_VALUE (PCMMSUBELEMENT_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_VALUE_TAG_ID_10544 ON PUBLIC.PCMM_PLANNING_VALUE (TAG_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_VALUE_USER_CREATION_ID_10541 ON PUBLIC.PCMM_PLANNING_VALUE (USER_CREATION_ID);
CREATE INDEX SYS_IDX_FK_PCMM_PLANNING_VALUE_USER_UPDATE_ID_10535 ON PUBLIC.PCMM_PLANNING_VALUE (USER_UPDATE_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10235_10236 ON PUBLIC.PCMM_PLANNING_VALUE (ID);


-- PUBLIC.PHENOMENAGROUP definition

-- Drop table

-- DROP TABLE PUBLIC.PHENOMENAGROUP;

CREATE TABLE PUBLIC.PHENOMENAGROUP (
	ID INTEGER NOT NULL IDENTITY,
	ID_LABEL VARCHAR(255),
	NAME VARCHAR(255),
	QOI_ID INTEGER,
	CONSTRAINT SYS_PK_10259 PRIMARY KEY (ID),
	CONSTRAINT FK_PHENOMENAGROUP_QOI_ID FOREIGN KEY (QOI_ID) REFERENCES PUBLIC.QOI(ID)
);
CREATE INDEX SYS_IDX_FK_PHENOMENAGROUP_QOI_ID_10550 ON PUBLIC.PHENOMENAGROUP (QOI_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10259_10260 ON PUBLIC.PHENOMENAGROUP (ID);


-- PUBLIC.PHENOMENON definition

-- Drop table

-- DROP TABLE PUBLIC.PHENOMENON;

CREATE TABLE PUBLIC.PHENOMENON (
	ID INTEGER NOT NULL IDENTITY,
	ID_LABEL VARCHAR(255),
	IMPORTANCE VARCHAR(255),
	NAME VARCHAR(255),
	PHENOMENONGROUP_ID INTEGER,
	CONSTRAINT SYS_PK_10255 PRIMARY KEY (ID),
	CONSTRAINT FK_PHENOMENON_PHENOMENONGROUP_ID FOREIGN KEY (PHENOMENONGROUP_ID) REFERENCES PUBLIC.PHENOMENAGROUP(ID)
);
CREATE INDEX SYS_IDX_FK_PHENOMENON_PHENOMENONGROUP_ID_10547 ON PUBLIC.PHENOMENON (PHENOMENONGROUP_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10255_10256 ON PUBLIC.PHENOMENON (ID);


-- PUBLIC.CRITERION definition

-- Drop table

-- DROP TABLE PUBLIC.CRITERION;

CREATE TABLE PUBLIC.CRITERION (
	ID INTEGER NOT NULL IDENTITY,
	NAME VARCHAR(255),
	"TYPE" VARCHAR(255),
	"VALUE" VARCHAR(16777216),
	PHENOMENON_ID INTEGER,
	CONSTRAINT SYS_PK_10147 PRIMARY KEY (ID),
	CONSTRAINT FK_CRITERION_PHENOMENON_ID FOREIGN KEY (PHENOMENON_ID) REFERENCES PUBLIC.PHENOMENON(ID)
);
CREATE INDEX SYS_IDX_FK_CRITERION_PHENOMENON_ID_10466 ON PUBLIC.CRITERION (PHENOMENON_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10147_10148 ON PUBLIC.CRITERION (ID);


-- PUBLIC.DOCUMENT definition

-- Drop table

-- DROP TABLE PUBLIC.DOCUMENT;

CREATE TABLE PUBLIC.DOCUMENT (
	ID INTEGER NOT NULL IDENTITY,
	LOCATION_URI VARCHAR(255),
	NAME VARCHAR(255),
	PHENOMENON_ID INTEGER,
	CONSTRAINT SYS_PK_10151 PRIMARY KEY (ID),
	CONSTRAINT FK_DOCUMENT_PHENOMENON_ID FOREIGN KEY (PHENOMENON_ID) REFERENCES PUBLIC.PHENOMENON(ID)
);
CREATE INDEX SYS_IDX_FK_DOCUMENT_PHENOMENON_ID_10469 ON PUBLIC.DOCUMENT (PHENOMENON_ID);
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10151_10152 ON PUBLIC.DOCUMENT (ID);