image: alpine:latest

# Add code source quality and security scan
include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml


stages:
  - test # check code with gitlab code quality check and SpotBugs
  - build # build the artifacts and launch unit tests
  - package # package the artifacts and import them into Gitlab Package Registry
  - release # create a new release (snapshot or stable) (create a tag and merge develop branch if necessary)
  - publish # publish documentation, p2 repository and javadoc from Gitlab Package Registry to Gitlab Pages


variables:
  MAVEN_CLI_OPTS: ""
  PROJECT_ROOT_POM: "src/gov.sandia.cf/"
  DS_JAVA_VERSION: 8
  DS_EXCLUDED_ANALYZERS: "gemnasium-maven"

# Workaround for Gitlab issue generating a detached pipeline for "rules" "if" "manual" jobs
workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE != "detached"'

#####################################
########## Stage test ############
#####################################

# Override code_quality job to keep report artifacts
code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]

# Override Gitlab job (spotbugs-sast)
spotbugs-sast:
  stage: test
  image: maven:3.5.4-jdk-8
  extends: []
  needs: []
  before_script:
    - echo "==================== [test] Installing GUI test dependencies ============="
    - apt-get update -y
    - apt-get install -y libgl1-mesa-dev libglu1-mesa xvfb
    - export DISPLAY=:99.0
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  script:
    - echo "==================== [test] Verifying cf plugin =========================="
    - cd $PROJECT_ROOT_POM
    - mvn $MAVEN_CLI_OPTS clean verify -DskipTests
  artifacts:
    reports:
      sast: src/gov.sandia.cf/tests/gov.sandia.cf.plugin.tests/target/spotbugsXml.xml


#####################################
########## Stage build ############
#####################################

# Test and Build:
#  - automatically if it is a branch
# (keep artifacts 3 days)
build and test:
  stage: build
  image: maven:3.5.4-jdk-8
  before_script:
    - echo "==================== [build] Installing GUI test dependencies ============"
    - apt-get update -y
    - apt-get install -y libgl1-mesa-dev libglu1-mesa xvfb graphviz
    - export DISPLAY=:99.0
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - echo "Creating artifacts folder"
    - mkdir target
    - mkdir target/build
    - mkdir target/coverage
  script:
    - echo "==================== [build] Building and testing CF plugin =============="
    - cd $PROJECT_ROOT_POM
    - mvn $MAVEN_CLI_OPTS clean install
    - echo "==================== [build] Copying build into the artifacts folder ====="
    - cp -R releng/gov.sandia.cf.update/target/site/. ../../target/build/
    - echo "==================== [build] Copying test coverage report into the artifacts folder"
    - cp -R tests/gov.sandia.cf.plugin.tests/target/coverage-site/. ../../target/coverage/
    - cp tests/gov.sandia.cf.plugin.tests/target/build-test.log ../../target/build-test.log
  artifacts:
    expire_in: 3 days
    paths:
      - target
    reports:
      junit: src/gov.sandia.cf/tests/gov.sandia.cf.plugin.tests/target/surefire-reports/TEST-*.xml
      cobertura: src/gov.sandia.cf/tests/gov.sandia.cf.plugin.tests/target/coverage-site/jacoco.xml
  rules:
    - if: '$CI_COMMIT_BRANCH'
    - when: never

# Test, Build and create Javadoc:
#  - automatically if it is a tag
# (keep artifacts for ever)
build and test tag:
  stage: build
  image: maven:3.5.4-jdk-8
  before_script:
    - echo "==================== [build] Installing GUI test dependencies ============"
    - apt-get update -y
    - apt-get install -y libgl1-mesa-dev libglu1-mesa xvfb graphviz
    - export DISPLAY=:99.0
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - echo "Creating artifacts folder"
    - mkdir target
    - mkdir target/build
    - mkdir target/coverage
    - mkdir target/javadoc
  script: 
    - echo "==================== [build] Building and testing CF plugin =============="
    - cd $PROJECT_ROOT_POM
    - mvn $MAVEN_CLI_OPTS clean install
    - echo "==================== [build] Copying build into the artifacts folder ====="
    - cp -R releng/gov.sandia.cf.update/target/site/. ../../target/build/
    - echo "==================== [build] Copying test coverage report into the artifacts folder"
    - cp -R tests/gov.sandia.cf.plugin.tests/target/coverage-site/. ../../target/coverage/
    - cp tests/gov.sandia.cf.plugin.tests/target/build-test.log ../../target/build-test.log
    # Generate Javadoc
    - echo "==================== [build] Generating CF Javadoc ======================="
    - cd bundles/gov.sandia.cf.plugin/
    - mvn javadoc:javadoc
    - cp -r target/site/apidocs/* ../../../../target/javadoc/
  artifacts:
    paths:
      - target
    reports:
      junit: src/gov.sandia.cf/tests/gov.sandia.cf.plugin.tests/target/surefire-reports/TEST-*.xml
      cobertura: src/gov.sandia.cf/tests/gov.sandia.cf.plugin.tests/target/coverage-site/jacoco.xml
  rules:
    - if: '$CI_COMMIT_TAG'
    - when: never

    
#####################################
########## Stage package ############
#####################################
  
# Package (builds and javadoc) into Gitlab package registry
#  - automatically if it is a tag
#  - manually if it is a protected branch (develop, master)
package:
  image: alpine:latest
  stage: package
  variables:
    PACKAGENAME: "gov.sandia.cf"
    P2_REPO_FILE_PREFIX: gov.sandia.cf.p2_repo
    JAVADOC_FILE_PREFIX: gov.sandia.cf.javadoc
    LATEST_VERSION: "latest"
  before_script:
    - echo "==================== [package] Install dependencies ======================"
    - apk update && apk add wget curl zip libxml2-utils jq git
  script:
    - mkdir target/package
    - export CF_VERSION=$(xmllint --xpath 'string(//site/feature/@version)' target/build/site.xml)
    - if [ -z "$CF_VERSION" ]; then echo "No version found. Impossible to continue package import job." && exit 1; else echo "CF Version $CF_VERSION"; fi;
    # Import p2 repository into Gitlab package registry
    - echo "==================== [package] Zipping CF build $CF_VERSION to prepare package import"
    - cd target/build/
    - zip -q -r ../package/$P2_REPO_FILE_PREFIX.$CF_VERSION.zip *
    - echo "==================== [package] Importing CF build target/package/$P2_REPO_FILE_PREFIX.$CF_VERSION.zip into Gitlab package registry $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/$PACKAGENAME/$CF_VERSION/$P2_REPO_FILE_PREFIX.$CF_VERSION.zip?status=default"
    - curl --user $DEPLOY_CREDENTIALS --upload-file ../package/$P2_REPO_FILE_PREFIX.$CF_VERSION.zip "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/$PACKAGENAME/$CF_VERSION/$P2_REPO_FILE_PREFIX.$CF_VERSION.zip?status=default"
    # Import javadoc (if it exists) into Gitlab package registry
    - if [ -d "../javadoc" ]; then echo "Zipping CF javadoc $CF_VERSION to prepare package import"; else echo "No javadoc found" && exit 0; fi
    - cd ../javadoc/
    - zip -q -r ../package/$JAVADOC_FILE_PREFIX.$CF_VERSION.zip *
    - echo "==================== [package] Importing CF javadoc target/package/$JAVADOC_FILE_PREFIX.$CF_VERSION.zip into Gitlab package registry $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/$PACKAGENAME/$CF_VERSION/$JAVADOC_FILE_PREFIX.$CF_VERSION.zip?status=default"
    - curl --user $DEPLOY_CREDENTIALS --upload-file ../package/$JAVADOC_FILE_PREFIX.$CF_VERSION.zip "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/$PACKAGENAME/$CF_VERSION/$JAVADOC_FILE_PREFIX.$CF_VERSION.zip?status=default"
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_BRANCH'
      when: manual
    - when: never
  allow_failure: true


#####################################
########### Stage release ############
#####################################

# Release a snapshot
#  - only manually if it is a protected branch
release snapshot:
  image: alpine:latest
  stage: release
  before_script:
    - echo "==================== [release] Install dependencies ======================"
    - 'which ssh-agent || ( apk update && apk add openssh-client)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - apk add libxml2-utils git
    - git config --global user.name "CF robot"
    - git config --global user.email "info@ng-analytics.com"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "==================== [release] Cloning CF git repository ================="
    - git clone git@gitlab.com:CredibilityFramework/cf.git cf
    - cd cf
    - echo "==================== [release] Checkout branch $BRANCH_DEVELOP ==========="
    - git checkout $CI_COMMIT_BRANCH
    - git branch -a
    - git status
    - export CF_VERSION=$(xmllint --xpath 'string(//site/feature/@version)' ../target/build/site.xml)
    - echo "==================== [release] Tag new CF build $CF_VERSION =============="
    - git tag -a $CF_VERSION -m "Autogenerated tag for version $CF_VERSION"
    - git push origin $CF_VERSION
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_BRANCH'
      when: manual
    - when: never
  allow_failure: true


# Release a stable version on the master branch
#  - only manually if it is the develop branch
# /!\ This jobs needs to define variable before execution: 'VERSION' before being executed otherwise it will trigger an error and exit job.
release in master:
  image: alpine:latest
  stage: release
  variables: 
    BRANCH_DEVELOP: "develop"
    BRANCH_MASTER: "master"
  before_script:
    - echo "==================== [release] Install dependencies ======================"
    - 'which ssh-agent || ( apk update && apk add openssh-client)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - apk add libxml2-utils git
    - git config --global user.name "CF robot"
    - git config --global user.email "info@ng-analytics.com"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "==================== [release] Cloning CF git repository ================="
    - git clone git@gitlab.com:CredibilityFramework/cf.git cf
    - cd cf
    - echo "==================== [release] Checkout branch $BRANCH_DEVELOP ==========="
    - git checkout $BRANCH_DEVELOP
    - export CF_VERSION=$(xmllint --xpath 'string(//site/feature/@version)' ../target/build/site.xml)
    - if [ $VERSION == $CF_VERSION ]; then echo "Version confirmation checked for build $CF_VERSION"; else echo "Version confirmation not good, entered version $VERSION does not match build version $CF_VERSION. This message protects from a mistake. Please confirm the version number by entering it manually in variable 'VERSION' before running this manual job." && exit 1; fi;
    - echo "==================== [release] Merge into $BRANCH_MASTER version $CF_VERSION" 
    - git checkout $BRANCH_MASTER
    - git branch -a
    - git status
    - git merge --no-ff $BRANCH_DEVELOP
    - git push
    - echo "==================== [release] Tag new CF build $CF_VERSION =============="
    - git tag -a $CF_VERSION -m "Autogenerated tag for version $CF_VERSION"
    - git push origin $CF_VERSION
    - echo "==================== [release] Rebase $BRANCH_DEVELOP on $BRANCH_MASTER =="
    - git checkout $BRANCH_DEVELOP
    - git branch -a
    - git status
    - git rebase $BRANCH_MASTER
    - git push origin $BRANCH_DEVELOP --force
  rules:
    - if: '$CI_COMMIT_BRANCH == $BRANCH_DEVELOP'
      when: manual
    - when: never
  allow_failure: true


#####################################
########## Stage publish ############
#####################################

# Publish documentation, p2 repository and javadoc from Gitlab Package Registry to Gitlab Pages:
#  - automatically if it is the 'master' branch or a tag
#  - manually if it is a protected branch (to avoid Gitlab Pages hack by another branch)
pages:
  image: ruby:2.7
  stage: publish
  variables: 
    PACKAGENAME: "gov.sandia.cf" # used into ci/doc/site/unzip-packages.sh script
    P2_REPO_FILE_PREFIX: "gov.sandia.cf.p2_repo" # used into ci/doc/site/unzip-packages.sh script
    JAVADOC_FILE_PREFIX: "gov.sandia.cf.javadoc" # used into ci/doc/site/unzip-packages.sh script
  before_script:
    - echo "==================== [publish] Install dependencies ===================="
    - apt-get update -y && apt-get install -y wget curl unzip findutils jq
  script:
    - echo "==================== [publish] Build documentation ====================="
    - echo "==================== [publish] Extracting CF Packages =================="  
    - . ci/doc/site/unzip-packages.sh doc/site/
    - echo "==================== [publish] Generating CF site pages to $CI_PAGES_URL"
    - . ci/doc/site/generate-pages.sh doc/site/
    - echo "==================== [publish] Creating Jekyll site ===================="
    - cd doc/site/
    - gem install jekyll bundler jekyll-remote-include
    - jekyll build -d ../../public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_TAG'
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_BRANCH'
      when: manual
    - when: never
  allow_failure: true
