--------------------------------------------------------
-- UPDATE field to allow long name for planning question
--------------------------------------------------------
-- PCMM - Generic Parameter
ALTER TABLE PCMM_PLANNING_PARAM ALTER COLUMN NAME LONGVARCHAR;
ALTER TABLE PCMM_PLANNING_QUESTION ALTER COLUMN NAME LONGVARCHAR;
ALTER TABLE PCMM_PLANNING_SELECT_VALUE ALTER COLUMN NAME LONGVARCHAR;

ALTER TABLE COM_UNCERTAINTY_PARAM ALTER COLUMN NAME LONGVARCHAR;
ALTER TABLE COM_UNCERTAINTY_SELECT_VALUE ALTER COLUMN NAME LONGVARCHAR;